swagger: '2.0'
info:
  description: |
    This is a training server
  version: "1.0.1"
  title: Nodejs mentoring programm
  termsOfService: http://swagger.io/terms/
  contact:
    email: andrei_kandratsenka@epam.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
- name: users
  description: Everithing about user
  externalDocs: 
    description: Find out more
    url: http://swagger.io
- name: products
  description: Everithing about products
  externalDocs:
    description: Find out more

    url: http://swagger.io
- name: cities
  description: Everithing about cities
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /users:
    get:
      tags:
      - users
      summary: return all users
      description: return all users from DB
      produces:
      - application/json
      responses:
        200:
          description: successful
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        404:
          description: Something went wrong
      security:
      - training_auth:
        - write:training
        - read:training
  /users/{userId}:
    get:
      tags:
      - users
      summary: return user by Id
      description: return user by Id
      produces:
      - application/json
      parameters:
      - name: userId
        in: path
        description: User id to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful
          schema:
            type: object
            items:
              $ref: '#/definitions/User'
        404:
          description: Something went wrong
      security:
      - training_auth:
        - write:training
        - read:training
    delete:
      tags:
      - users
      summary: delete single user by Id
      description: delete single user by Id
      produces:
      - application/json
      parameters:
      - name: userId
        in: path
        description: User id to delete
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Successful
        404:
          description: Something went wrong
      security:
      - training_auth:
        - write:training
        - read:training
  /products:
    get:
      tags:
      - products
      summary: Return all products
      description: Return all products
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        404:
          description: Somthing went wrong
      security:
      - training_auth:
        - write:training
        - read:training
    post:
      tags:
      - products
      summary: Save new product
      operationId: saveNewProduct
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: order placed for purchasing the pet
        required: true
        schema:
          $ref: '#/definitions/Product' 
      responses:
        200:
          description: Successful
          schema:
            type: object
            items:
              $ref: '#/definitions/Product'
        404:
          description: Somthing went wrong
      security:
      - training_auth:
        - write:training
        - read:training
  /products/{productId}:
    get:
      tags:
      - products
      summary: Return all products
      description: Return all products
      produces:
      - application/json
      parameters:
      - name: productId
        in: path
        description: User id to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        404:
          description: Somthing went wrong
      security:
      - training_auth:
        - write:training
        - read:training
    delete:
      tags:
      - products
      summary: delete single product by Id
      description: delete single product by Id
      produces:
      - application/json
      parameters:
      - name: productId
        in: path
        description: Product id to delete
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Successful
        404:
          description: Something went wrong
      security:
      - training_auth:
        - write:training
        - read:training
  /products/{productId}/reviews:
    get:
      tags:
      - products
      summary: Return product reviews by Id
      description: Return product reviews by Id
      produces:
      - application/json
      parameters:
      - name: productId
        in: path
        description: Product id to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Successful
          schema:
            type: object
            items:
              $ref: '#/definitions/Product'
        404:
          description: Something went wrong
      security:
      - training_auth:
        - write:training
        - read:training
  /cities:
    get:
      tags:
      - cities
      summary: return all cities
      description: return all cities from DB
      produces:
      - application/json
      responses:
        200:
          description: successful
          schema:
            type: array
            items:
              $ref: '#/definitions/City'
        404:
          description: Something went wrong
      security:
      - training_auth:
        - write:training
        - read:training
    post:
      tags:
      - cities
      summary: Save new city
      operationId: saveNewCity
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: order placed for purchasing the pet
        required: true
        schema:
          $ref: '#/definitions/City' 
      responses:
        200:
          description: Successful
          schema:
            type: object
            items:
              $ref: '#/definitions/Product'
        404: 
          description: Somthing went wrong
      security:
      - training_auth:
        - write:training
        - read:training
  /cities/{cityId}:
    put:
      tags:
      - cities
      summary: Save new city
      operationId: updateCity
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - name: cityId
        in: path
        description: City id to delete
        required: true
        type: integer
        format: int64
      - in: body
        name: body
        description: order placed for purchasing the pet
        required: true
        schema:
          $ref: '#/definitions/City' 
      responses:
        200:
          description: Successful
          schema:
            type: object
            items:
              $ref: '#/definitions/Product'
        404: 
          description: Somthing went wrong
      security:
      - training_auth:
        - write:training
        - read:training
    delete:
      tags:
      - cities
      summary: Delete city by Id
      operationId: delete City
      produces:
      - application/json
      parameters:
      - name: cityId
        in: path
        description: City id to delete
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Successful
          schema:
            type: object
            items:
              $ref: '#/definitions/Product'
        404: 
          description: Somthing went wrong
      security:
      - training_auth:
        - write:training
        - read:training
securityDefinitions:
  training_auth:
    type: oauth2
    authorizationUrl: localhost:3000/auth/twitter
    flow: implicit
    scopes:
      write:training: modify data in application
      read:training: read any data in application
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      userName:
        type: string
      lastName:
        type: string
      email:
        type: string
  Product:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      brand:
        type: string
      price:
        type: number
      color:
        type: string
      size:
        type: string
        description: Good size
        enum:
        - L
        - M
        - XL
        - XXL
  City:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      country:
        type: string
      capital:
        type: boolean
      lat:
        type: number
      long:
        type: number
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
# Added by API Auto Mocking Plugin
host: localhost:10010
basePath: /api
schemes:
 - http